on:
  pull_request:
    branches:
      - master

name: check-link-rot

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  check-link-rot:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: "3.1"

      - uses: r-lib/actions/setup-r@v2
        with:
          #r-version: "devel"
          http-user-agent: "release"
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          pak-version: devel
          dependencies: '"hard"'
          extra-packages: |
            any::rcmdcheck
            any::urlchecker
      - name: Run URL checker
        run: |
          options(crayon.enabled = TRUE)
          rotten_links <- urlchecker::url_check(progress = FALSE)
          print(rotten_links)
          if (length(rotten_links$URL) > 0L) {
            cli::cli_abort("Some URLs are outdated and need to be updated.")
          }
        shell: Rscript {0}
